// app/admin/vip-rewards/types.ts
// VIP Rewards screen types based on AdminFlows.md Screen 4 wireframe

// =============================================================================
// ENUMS
// =============================================================================

/** Reward type options */
export type RewardType =
  | 'gift_card'
  | 'commission_boost'
  | 'spark_ads'
  | 'discount'
  | 'physical_gift'
  | 'experience'

/** Reward type display mapping */
export const REWARD_TYPE_LABELS: Record<RewardType, string> = {
  gift_card: 'Gift Card',
  commission_boost: 'Commission Boost',
  spark_ads: 'Spark Ads',
  discount: 'Discount',
  physical_gift: 'Physical Gift',
  experience: 'Experience'
}

/** Tier eligibility options (no 'all' for VIP rewards - must be specific tier) */
export type TierEligibility = 'tier_1' | 'tier_2' | 'tier_3' | 'tier_4' | 'tier_5' | 'tier_6'

/** Tier display mapping */
export const TIER_LABELS: Record<TierEligibility, string> = {
  tier_1: 'Bronze',
  tier_2: 'Silver',
  tier_3: 'Gold',
  tier_4: 'Platinum',
  tier_5: 'Diamond',
  tier_6: 'Elite'
}

/** Redemption frequency options */
export type RedemptionFrequency = 'one-time' | 'monthly' | 'weekly' | 'unlimited'

/** Frequency display mapping */
export const FREQUENCY_LABELS: Record<RedemptionFrequency, string> = {
  'one-time': 'One-time',
  'monthly': 'Monthly',
  'weekly': 'Weekly',
  'unlimited': 'Unlimited'
}

/** Size category options for physical gifts */
export type SizeCategory = 'clothing' | 'shoes' | 'accessories'

// =============================================================================
// VALUE DATA (JSONB structures by reward type)
// =============================================================================

/** Gift card value data */
export interface GiftCardValueData {
  amount: number                      // @backend: rewards.value_data.amount
}

/** Commission boost value data */
export interface CommissionBoostValueData {
  percent: number                     // @backend: rewards.value_data.percent
  durationDays: number                // @backend: rewards.value_data.duration_days
}

/** Spark ads value data */
export interface SparkAdsValueData {
  amount: number                      // @backend: rewards.value_data.amount
}

/** Discount value data */
export interface DiscountValueData {
  percent: number                     // @backend: rewards.value_data.percent
  durationMinutes: number             // @backend: rewards.value_data.duration_minutes
  couponCode: string                  // @backend: rewards.value_data.coupon_code
  maxUses: number | null              // @backend: rewards.value_data.max_uses (NULL = unlimited)
}

/** Physical gift value data */
export interface PhysicalGiftValueData {
  requiresSize: boolean               // @backend: rewards.value_data.requires_size
  sizeCategory: SizeCategory | null   // @backend: rewards.value_data.size_category
  sizeOptions: string[]               // @backend: rewards.value_data.size_options
  displayText: string                 // @backend: rewards.value_data.display_text (max 27 chars)
}

/** Experience value data */
export interface ExperienceValueData {
  displayText: string                 // @backend: rewards.value_data.display_text (max 27 chars)
}

/** Union type for all value data */
export type ValueData =
  | GiftCardValueData
  | CommissionBoostValueData
  | SparkAdsValueData
  | DiscountValueData
  | PhysicalGiftValueData
  | ExperienceValueData

// =============================================================================
// TABLE DISPLAY
// =============================================================================

/** VIP Reward item for table display */
export interface VipRewardItem {
  id: string                          // @backend: rewards.id
  name: string                        // @backend: rewards.name (auto-generated by backend)
  type: RewardType                    // @backend: rewards.type
  typeFormatted: string               // @backend: computed by server
  tierEligibility: TierEligibility    // @backend: rewards.tier_eligibility
  tierFormatted: string               // @backend: computed by server ("Bronze", "Silver", etc.)
  redemptionFrequency: RedemptionFrequency  // @backend: rewards.redemption_frequency
  frequencyFormatted: string          // @backend: computed by server
  enabled: boolean                    // @backend: rewards.enabled
  statusFormatted: string             // @backend: computed by server ("Active", "Inactive")
}

// =============================================================================
// DRAWER DETAIL (for Create/Edit)
// =============================================================================

/** Full VIP reward details for create/edit drawer */
export interface VipRewardDetails {
  id: string | null                   // @backend: rewards.id (null for new)
  type: RewardType                    // @backend: rewards.type
  description: string | null          // @backend: rewards.description (max 12 chars, physical_gift/experience only)
  valueData: ValueData                // @backend: rewards.value_data (JSONB)
  tierEligibility: TierEligibility    // @backend: rewards.tier_eligibility
  previewFromTier: TierEligibility | null  // @backend: rewards.preview_from_tier
  redemptionFrequency: RedemptionFrequency  // @backend: rewards.redemption_frequency
  redemptionQuantity: number | null   // @backend: rewards.redemption_quantity (1-10, NULL for unlimited)
  enabled: boolean                    // @backend: rewards.enabled
  // Joined/computed data
  name: string | null                 // @backend: rewards.name (auto-generated, for display)
}

// =============================================================================
// API RESPONSE
// =============================================================================

/** VIP Rewards list API response */
export interface VipRewardsResponse {
  rewards: VipRewardItem[]
  totalCount: number                  // @backend: computed by server
  totalCountFormatted: string         // @backend: computed by server
}

// =============================================================================
// STATUS BADGE CONFIG
// =============================================================================

export const REWARD_STATUS_CONFIG: Record<string, { label: string; variant: 'gray' | 'green' }> = {
  active: { label: 'Active', variant: 'green' },
  inactive: { label: 'Inactive', variant: 'gray' }
}

// =============================================================================
// DEFAULT VALUE DATA BY TYPE
// =============================================================================

export const DEFAULT_VALUE_DATA: Record<RewardType, ValueData> = {
  gift_card: { amount: 0 },
  commission_boost: { percent: 0, durationDays: 7 },
  spark_ads: { amount: 0 },
  discount: { percent: 0, durationMinutes: 1440, couponCode: '', maxUses: null },
  physical_gift: { requiresSize: false, sizeCategory: null, sizeOptions: [], displayText: '' },
  experience: { displayText: '' }
}
